### ISSUE TITLE
Readers can get the real code from github.com/mbeyeler/opencv-machine-learning

### ISSUE THREAD

**Issue by mbeyeler** [PacktPublishing/Machine-Learning-for-OpenCV#2]
Hi,

I'm the author of this book and afraid to say that - in the current state - this repository is useless, because it doesn't contain the actual source code. For most chapters, only the (confidential) reviewer instructions are present. For a small number of chapters, only outdated code is present.

Readers can get the real, up-to-date code from https://github.com/mbeyeler/opencv-machine-learning.  You will be in good company - the repo has already gathered >100 stars and >40 forks.

@Danish-Shaikh123: In order to have the Packt profile point to the real code, please consider the following:
1. Delete this repository.
2. Go to my GitHub profile (see link above) and fork the project. This will make the repository show up on your profile again, this time with the actual code. In addition, this will make it easier to sync with the original repository, and readers know where the source is. You can still adjust the README to your liking (e.g., by adding the Related products section).

Thanks and all the best,
Michael

**Comment by sohamapackt** [comment]
Hi @mbeyeler ,

Thanks for the update!
I am closing the issue, in case you wish to add more details to this, feel free to reopen it. 

Thanks.
